export function graphUiSvgHelpersScript(): string {
  return String.raw`
function zoomCurrentSvg(factor){const svg=canvas.querySelector('svg');if(!svg)return;const rect=svg.getBoundingClientRect(),box=(svg.getAttribute('viewBox')||('0 0 '+rect.width+' '+rect.height)).split(' ').map(Number),nw=box[2]*factor,nh=box[3]*factor;svg.setAttribute('viewBox',[box[0]+(box[2]-nw)/2,box[1]+(box[3]-nh)/2,nw,nh].join(' '))}
function visibleRootBounds(svg,root){const content=root.getBoundingClientRect(),inverse=svg.getScreenCTM()?.inverse();if(!inverse)return null;const point=(x,y)=>{const value=svg.createSVGPoint();value.x=x;value.y=y;return value.matrixTransform(inverse)},topLeft=point(content.left,content.top),bottomRight=point(content.right,content.bottom);return{x:topLeft.x,y:topLeft.y,width:bottomRight.x-topLeft.x,height:bottomRight.y-topLeft.y}}
function fitCurrentSvg(maxZoom=Infinity){const svg=canvas.querySelector('svg'),root=svg?.querySelector(':scope > g');if(!svg||!root)return null;let bounds;try{bounds=visibleRootBounds(svg,root)}catch{return null}if(!bounds||!Number.isFinite(bounds.x)||bounds.width<=0||bounds.height<=0)return null;const rect=svg.getBoundingClientRect(),viewportW=rect.width||canvas.clientWidth||900,viewportH=rect.height||canvas.clientHeight||650,pad=Math.max(28,Math.min(72,Math.max(bounds.width,bounds.height)*.08));let x=bounds.x-pad,y=bounds.y-pad,w=bounds.width+pad*2,h=bounds.height+pad*2;const viewportRatio=viewportW/viewportH,contentRatio=w/h;if(contentRatio>viewportRatio){const fittedH=w/viewportRatio;y-=(fittedH-h)/2;h=fittedH}else{const fittedW=h*viewportRatio;x-=(fittedW-w)/2;w=fittedW}if(Number.isFinite(maxZoom)&&(w<viewportW/maxZoom||h<viewportH/maxZoom)){const centerX=x+w/2,centerY=y+h/2,scale=Math.max(viewportW/maxZoom/w,viewportH/maxZoom/h);w*=scale;h*=scale;x=centerX-w/2;y=centerY-h/2}const box=[x,y,w,h].join(' ');svg.setAttribute('viewBox',box);return box}
function fitCurrentSvgIfNeeded(maxZoom=1.4){const svg=canvas.querySelector('svg'),root=svg?.querySelector(':scope > g');if(!svg||!root)return null;const viewport=svg.getBoundingClientRect(),content=root.getBoundingClientRect(),margin=Math.max(18,Math.min(viewport.width,viewport.height)*.035),outside=content.left<viewport.left+margin||content.top<viewport.top+margin||content.right>viewport.right-margin||content.bottom>viewport.bottom-margin;if(!outside)return null;return fitCurrentSvg(maxZoom)}
function fitHighlightedMap(){const dimmed=[...canvas.querySelectorAll('.map-community.is-dimmed,.map-community-link.is-dimmed')],previous=dimmed.map(element=>element.style.display);dimmed.forEach(element=>element.style.display='none');const fitted=fitCurrentSvgIfNeeded(1.4);dimmed.forEach((element,index)=>element.style.display=previous[index]);return fitted}
`;
}
