import { graphAppCss } from './ui/styles.ts';
import { graphAppScript } from './ui/script.ts';

export function renderWikiGraphV2(): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wiki Graph</title><script src="/assets/d3.min.js"></script><style>${graphAppCss}
.map-community{cursor:pointer;transition:opacity .2s}.map-halo{fill-opacity:.16;stroke:#b9d9ff;stroke-opacity:.38;transform:scale(.78)}.map-center{r:8px}.map-doc{r:2.5px}.map-center,.map-doc{stroke:#d8eaff;stroke-width:.7}.map-label,.map-count,.map-community-link text{text-anchor:middle;fill:#eef5ff;paint-order:stroke;stroke:#08111d;stroke-width:3px}.map-label{font-weight:700;font-size:13px}.map-count{font-size:10px;fill:#9fb0c3}.map-community-link line{stroke:#93a9c2;stroke-opacity:.58;stroke-width:1px}.map-community-link text{font-size:10px}.selection-chain-link{stroke:#fff;stroke-width:2.5px;stroke-opacity:1;filter:drop-shadow(0 0 5px #4d9cff)}.is-dimmed{opacity:.06!important}.is-highlighted{opacity:1!important}.node.is-highlighted circle{stroke:#fff;stroke-width:3px;filter:drop-shadow(0 0 7px #75aff5)}.link.is-highlighted{stroke-opacity:1;stroke-width:3px}.list-table .is-highlighted{background:#1d4775;color:#fff}.map-community.is-highlighted .map-halo{fill-opacity:.4;stroke-opacity:1;stroke-width:3px}.focus-column-title,.focus-community-caption{text-anchor:middle;fill:#b9c8d9;font-size:11px;text-transform:uppercase}.focus-community-caption{fill:#75aff5}.focus-card{cursor:pointer}.focus-card rect{fill:#111f2d;stroke:#34485e}.focus-card.member rect{fill:#2b1850;stroke:#a75ee8;stroke-width:2px}.focus-card:hover rect{stroke:#fff}.focus-title{fill:#f1f6fc;font-size:12px}.focus-type{fill:#8294a8;font-size:10px}.focus-link{fill:none;stroke:#72a7e8;stroke-width:1.5;stroke-opacity:.75}.focus-link.external{stroke-dasharray:5 4;stroke:#74c365}
.spacing-control{display:flex;align-items:center;gap:7px;color:#9fb0c3;font-size:11px}.spacing-control[hidden]{display:none}.spacing-control input{width:120px;accent-color:#4d9cff}.spacing-control output{min-width:36px;color:#dce9f8}.inspector .community-item{display:block;width:100%;text-align:left!important;justify-content:flex-start;align-items:flex-start;padding-left:6px}
.graph-search{position:relative;margin-left:auto;width:min(520px,38vw);display:grid;grid-template-columns:minmax(180px,1fr) auto;gap:6px}header .graph-search input{width:100%;margin:0}.reset-search{white-space:nowrap;padding:.45rem .65rem}.graph-search-results{position:absolute;z-index:20;left:0;right:92px;top:calc(100% + 4px);background:#0d1825;border:1px solid #34485e;border-radius:7px;padding:4px;box-shadow:0 12px 30px #0009}.graph-search-item{display:block;width:100%;border:0;background:transparent;text-align:left;padding:7px 9px}.graph-search-item:hover,.graph-search-item.active{background:#1d4775}.graph-search-item small{display:block;color:#8fa1b5;margin-top:2px}.community-doc.selected{color:#fff;background:#245a9e;border-left:3px solid #75aff5;font-weight:700}.focus-caption-overlay{position:absolute;z-index:5;left:50%;bottom:12px;transform:translateX(-50%);max-width:80%;padding:7px 12px;border:1px solid #34485e;border-radius:6px;background:#08131ee8;color:#75aff5;font-size:11px;text-align:center;white-space:nowrap;pointer-events:none}
.group-link{stroke-dasharray:5 5}.group-link.is-highlighted{stroke-dasharray:5 5}
.document-preview-overlay{position:fixed;z-index:50;right:8px;top:56px;width:50vw;height:calc(100vh - 64px);max-height:calc(100vh - 64px);display:flex;min-height:0;flex-direction:column;overflow:hidden;background:#0b1622f7;border:1px solid #3c536c;border-radius:8px;box-shadow:0 18px 50px #000c}.document-preview-overlay[hidden]{display:none}.document-preview-head{display:flex;flex:none;align-items:center;justify-content:space-between;padding:10px 12px;border-bottom:1px solid #34485e}.document-preview-content{flex:1;min-height:0;overflow-y:auto;overscroll-behavior:contain;padding:18px 22px}.document-preview-content img{max-width:100%}.show-document-preview{width:100%;margin-top:10px;background:#245a9e}
.community-relation-legend{position:absolute;z-index:4;left:10px;bottom:10px;display:flex;gap:10px;flex-wrap:wrap;padding:7px 9px;background:#08131ee8;border:1px solid #34485e;border-radius:6px;color:#9fb0c3;font-size:10px}.community-relation-legend span:before{content:'';display:inline-block;width:14px;height:2px;margin:0 5px 3px 0;background:var(--c)}.community-relation-legend .dotted:before{height:0;border-top:2px dashed #93a9c2;background:transparent}
#document-preview-title{text-transform:uppercase}.inspector{position:relative}.inspector-toggle{position:sticky;z-index:3;top:0;float:right;padding:.3rem .5rem}.inspector-collapsed{grid-template-columns:var(--left-w) 5px minmax(500px,1fr) 42px}.inspector-collapsed .inspector{padding:6px;align-items:center;overflow:hidden}.inspector-collapsed .inspector-toggle{align-self:center;float:none;margin:0}.inspector-collapsed .inspector>:not(.inspector-toggle){display:none!important}.stage:fullscreen{width:100vw;height:100vh;border:0;border-radius:0;background:#08111d}.stage:fullscreen #canvas{min-height:0}
.relation-breakdown-item{padding:6px 7px;margin:2px 0;border-radius:5px;cursor:pointer;transition:background .15s,color .15s}.relation-breakdown-item:hover{background:#1d4775;color:#fff}.relation-breakdown-item.locked{background:#245a9e;color:#fff;box-shadow:inset 3px 0 #75aff5}
.stage-head>div:last-child{display:flex;flex-wrap:nowrap;align-items:center;gap:4px;white-space:nowrap;flex:none}.stage-head>div:last-child button{flex:0 0 auto;white-space:nowrap}.stage-head>div:first-child{min-width:0}.stage-head .spacing-control{flex:0 1 auto;min-width:150px}
.map-label{font-size:17px!important}.map-count{font-size:13px!important}.inspector{display:flex;flex-direction:column;overflow:hidden!important}.inspector-toggle{flex:none;align-self:flex-end}.inspector #inspector{display:flex;flex:1;min-height:0;flex-direction:column;overflow:hidden}.inspector .relation-breakdown{flex:1;min-height:90px;overflow-y:auto;overscroll-behavior:contain}.inspector .show-document-preview{flex:none}.inspector .card:not(.relation-breakdown){flex:none}
.theme-toggle{flex:none;width:38px;height:34px;padding:0;font-size:17px}.theme-light{color-scheme:light;--bg:#eef3f8;--panel:#fff;--soft:#e8eef5;--line:#b8c6d5;--text:#172433;--muted:#5f7082}.theme-light body{background:radial-gradient(circle at 55% 25%,#fff 0,#e8eef5 60%);color:var(--text)}body.theme-light{background:radial-gradient(circle at 55% 25%,#fff 0,#e8eef5 60%);color:var(--text)}body.theme-light header{background:#f8fbfddd;border-color:#b8c6d5}body.theme-light .brand{color:#172433}body.theme-light .filters,body.theme-light .inspector,body.theme-light .stage{background:#ffffffeb}body.theme-light button,body.theme-light input{color:#172433;background:#edf3f8;border-color:#b8c6d5}body.theme-light button:hover,body.theme-light button.active{background:#cfe3fb;border-color:#5d91cc}body.theme-light .graph-search-results,body.theme-light .document-preview-overlay{background:#fff;color:#172433}body.theme-light .map-label,body.theme-light .map-count,body.theme-light .map-community-link text,body.theme-light .node text{fill:#172433;stroke:#f7fafc}body.theme-light .focus-title{fill:#172433}body.theme-light .focus-card rect{fill:#f5f8fb;stroke:#8fa3b8}body.theme-light .focus-card.member rect{fill:#eadcff;stroke:#8354bf}body.theme-light .community-relation-legend,body.theme-light .focus-caption-overlay,body.theme-light .relation-legend{background:#fffffff0;color:#40556a}
.community-doc:before{content:'– ';color:var(--muted);font-weight:400}.community-doc.selected:before{color:#fff}
.inspector-toggle svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.inspector-toggle .icon-expand{display:none}.inspector-collapsed .inspector-toggle .icon-collapse{display:none}.inspector-collapsed .inspector-toggle .icon-expand{display:block}
</style></head><body>
<header><a class="brand" href="/">⌘ LLM-WIKI</a><span>←</span><strong>Wiki Graph</strong><div class="graph-search"><input id="search" type="search" autocomplete="off" placeholder="Search documents, topics, or tags…"><button id="reset-search" class="reset-search" type="button" title="Reset search, filters, and selection">Reset</button><div id="graph-search-results" class="graph-search-results" hidden></div></div><nav>${['map:Map','community:Community','focus:Focus','list:List'].map((item) => { const [id,label]=item.split(':'); return `<button data-view="${id}"${id==='map'?' class="active"':''}>${label}</button>`; }).join('')}</nav><button id="theme-toggle" class="theme-toggle" type="button" title="Switch to light theme" aria-label="Switch color theme">☀</button></header>
<main><aside class="filters"><h3>Filters</h3><div id="filters"></div><h3>Communities</h3><div id="community-list"></div></aside><div class="left-resizer" role="separator" aria-orientation="vertical" title="Resize filters"></div><section class="stage"><div class="stage-head"><div><b id="view-title">Global map view</b><small id="summary">Loading graph…</small></div><label class="spacing-control" id="spacing-control">Spacing <input id="map-spacing" type="range" min="70" max="300" value="150"><output id="map-spacing-value">150%</output></label><div><button id="focus-back" hidden>← Back</button><button id="zoom-out">−</button><button id="zoom-in">+</button><button id="fit">Fit</button><button id="fullscreen" title="Fullscreen">⛶</button></div></div><div id="canvas"><div class="relation-legend"><span style="--c:#72a7e8">Link</span><span style="--c:#9f7aea">Citation</span><span style="--c:#74c365">Generated from</span><span style="--c:#e4b44c">Template</span><span style="--c:#44c2c7">Context</span><span style="--c:#ed7d4d">Produces</span></div><div class="loading">Computing communities…</div></div></section><aside class="inspector"><button id="inspector-toggle" class="inspector-toggle" title="Collapse panel"><svg class="icon-collapse" viewBox="0 0 24 24"><path d="M8 3v5H3M16 21v-5h5M3 8l6-6M21 16l-6 6"/></svg><svg class="icon-expand" viewBox="0 0 24 24"><path d="M3 9V3h6M21 15v6h-6M3 3l7 7M21 21l-7-7"/></svg></button><div id="inspector"><h3>Selection</h3><p>Select a community or document to explore its relations.</p></div></aside></main>
<div id="document-preview-overlay" class="document-preview-overlay" hidden><div class="document-preview-head"><strong id="document-preview-title">Document preview</strong><button id="close-document-preview" type="button">Close</button></div><div id="document-preview-content" class="document-preview-content"></div></div><script>${graphAppScript}</script></body></html>`;
}
